
  CREATE TABLE "CMX_PRECO" 
   (	"ID_PRECO" NUMBER, 
	"CLASS_ID" NUMBER, 
	"TIP_PLANO" VARCHAR2(10), 
	"PLANO" VARCHAR2(10), 
	"FREQUENCIA" VARCHAR2(10), 
	"VALOR" NUMBER, 
	"ATIVO" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	 CONSTRAINT "CMX_PRECO_PK" PRIMARY KEY ("ID_PRECO")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CMX_PRECO_UK" UNIQUE ("CLASS_ID", "TIP_PLANO", "PLANO", "FREQUENCIA")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CMX_PRECO_CK" CHECK (ATIVO   IN ('Y', 'N')) ENABLE
   ) ;

  ALTER TABLE "CMX_PRECO" ADD CONSTRAINT "CMX_PRECO_CLASS_ID_FK" FOREIGN KEY ("CLASS_ID")
	  REFERENCES "CMX_CLASS" ("CLASS_ID") ENABLE;