
  CREATE TABLE "CMX_INCHARGE" 
   (	"INCHARGE_ID" NUMBER, 
	"NAME" VARCHAR2(50), 
	"CPF" VARCHAR2(50), 
	"EMAIL" VARCHAR2(50), 
	"PHONE" VARCHAR2(20), 
	 CONSTRAINT "CMX_INCHARGE_PK" PRIMARY KEY ("INCHARGE_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CMX_INCHARGE_UK" UNIQUE ("CPF")
  USING INDEX  ENABLE
   ) ;