
  CREATE TABLE "CMX_FATURA" 
   (	"ANO_MES" NUMBER, 
	"STUDANT_ID" NUMBER, 
	"STATUS" VARCHAR2(20), 
	"RG_CPF" VARCHAR2(20), 
	"RESPONSAVEL" VARCHAR2(50), 
	"CPF" VARCHAR2(13), 
	"TELEFONE" VARCHAR2(13), 
	"CLASS_ID" NUMBER, 
	"TIP_PLANO" VARCHAR2(13), 
	"PLANO" VARCHAR2(13), 
	"FREQUENCIA" VARCHAR2(13), 
	"VALOR_FATURA" NUMBER, 
	"DT_FATURA" VARCHAR2(10), 
	"DT_GEROU_FAT" VARCHAR2(10), 
	 CONSTRAINT "CMX_FATURA_UK" UNIQUE ("ANO_MES", "STUDANT_ID", "PLANO", "RG_CPF", "CPF", "TIP_PLANO", "FREQUENCIA")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "CMX_FATURA" ADD CONSTRAINT "CMX_FATURA_FK" FOREIGN KEY ("CLASS_ID")
	  REFERENCES "CMX_CLASS" ("CLASS_ID") ENABLE;