
  CREATE TABLE "CMX_TEAM" 
   (	"TEAM_ID" NUMBER NOT NULL ENABLE, 
	"TEACHER_ID" NUMBER NOT NULL ENABLE, 
	"CLASS_ID" NUMBER NOT NULL ENABLE, 
	"TIME_ID" NUMBER NOT NULL ENABLE, 
	"TEAM_SIZE" NUMBER NOT NULL ENABLE, 
	"CREATION_DATE" DATE, 
	"LAST_UPDATE_DATE" DATE, 
	 CONSTRAINT "CMX_TEAM_UK" UNIQUE ("TEACHER_ID", "CLASS_ID", "TIME_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CMX_TEAM_PK" PRIMARY KEY ("TEAM_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "CMX_TEAM" ADD CONSTRAINT "CMX_TEAM_CLASS_ID_FK" FOREIGN KEY ("CLASS_ID")
	  REFERENCES "CMX_CLASS" ("CLASS_ID") ENABLE;
  ALTER TABLE "CMX_TEAM" ADD CONSTRAINT "CMX_TEAM_TEACHER_ID_FK" FOREIGN KEY ("TEACHER_ID")
	  REFERENCES "CMX_TEACHER" ("TEACHER_ID") ENABLE;
  ALTER TABLE "CMX_TEAM" ADD CONSTRAINT "CMX_TEAM_TIME_ID_FK" FOREIGN KEY ("TIME_ID")
	  REFERENCES "CMX_TIME" ("TIME_ID") ENABLE;