
  CREATE TABLE "CMX_ERRO_LOG" 
   (	"CLASS_ID" NUMBER NOT NULL ENABLE, 
	"TIP_PLANO" VARCHAR2(13 CHAR) NOT NULL ENABLE, 
	"PLANO" VARCHAR2(13 CHAR), 
	"FREQUENCIA" VARCHAR2(13 CHAR), 
	"MENSAGEM" VARCHAR2(50)
   ) ;