
  CREATE TABLE "CMX_STUDANT" 
   (	"STUDANT_ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"DT_BIRTH" DATE NOT NULL ENABLE, 
	"RG_CPF" VARCHAR2(14) NOT NULL ENABLE, 
	"FLAG_STATUS" CHAR(1) DEFAULT 'I' NOT NULL ENABLE, 
	"DT_STATUS" DATE NOT NULL ENABLE, 
	"FLAG_CONTRACT" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"TEAM_ID" NUMBER, 
	"INCHARGE_ID" NUMBER, 
	"FLAG_MONDAY" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"FLAG_TUESDAY" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"FLAG_WEDNESDAY" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"FLAG_THURSDAY" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"FLAG_FRIDAY" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"TIP_PLANO" VARCHAR2(10) NOT NULL ENABLE, 
	"PLANO" VARCHAR2(10) NOT NULL ENABLE, 
	 CONSTRAINT "CMX_STUDANT_PK" PRIMARY KEY ("STUDANT_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CMX_STUDANT_UK" UNIQUE ("RG_CPF")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CMX_STUDANT_FLAG_TUES_CK" CHECK (FLAG_TUESDAY   IN ('Y', 'N')) ENABLE, 
	 CONSTRAINT "CMX_STUDANT_FLAG_THUR_CK" CHECK (FLAG_THURSDAY  IN ('Y', 'N')) ENABLE, 
	 CONSTRAINT "CMX_STUDANT_FLAG_MONDAY_CK" CHECK (FLAG_MONDAY   IN ('Y', 'N')) ENABLE, 
	 CONSTRAINT "CMX_STUDANT_FLAG_WEDN_CK" CHECK (FLAG_WEDNESDAY IN ('Y', 'N')) ENABLE, 
	 CONSTRAINT "CMX_STUDANT_FLAG_FRID_CK" CHECK (FLAG_FRIDAY    IN ('Y', 'N')) ENABLE
   ) ;

  ALTER TABLE "CMX_STUDANT" ADD CONSTRAINT "CMX_STUDANT_INCHARGE_ID_FK" FOREIGN KEY ("INCHARGE_ID")
	  REFERENCES "CMX_INCHARGE" ("INCHARGE_ID") ENABLE;
  ALTER TABLE "CMX_STUDANT" ADD CONSTRAINT "CMX_STUDANT_TEAM_ID_FK" FOREIGN KEY ("TEAM_ID")
	  REFERENCES "CMX_TEAM" ("TEAM_ID") ENABLE;