
  CREATE TABLE "CMX_SALA" 
   (	"SALA_ID" NUMBER, 
	"SALA" VARCHAR2(20), 
	 CONSTRAINT "CMX_SALA_PK" PRIMARY KEY ("SALA_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CMX_SALA_UK" UNIQUE ("SALA")
  USING INDEX  ENABLE
   ) ;