
  CREATE TABLE "CMX_TIME" 
   (	"TIME_ID" NUMBER NOT NULL ENABLE, 
	"TIME" VARCHAR2(200) NOT NULL ENABLE, 
	"FLAG_MONDAY" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"FLAG_TUESDAY" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"FLAG_WEDNESDAY" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"FLAG_THURSDAY" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"FLAG_FRIDAY" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"CREATION_DATE" DATE, 
	"LAST_UPDATE_DATE" DATE, 
	"SALA_ID" NUMBER, 
	 CONSTRAINT "CMX_TIME_PK" PRIMARY KEY ("TIME_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CMX_TIME_UK" UNIQUE ("TIME", "SALA_ID", "FLAG_MONDAY", "FLAG_TUESDAY", "FLAG_WEDNESDAY", "FLAG_THURSDAY", "FLAG_FRIDAY")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "CMX_TIME" ADD CONSTRAINT "CMX_TIME_SALA_ID_FK" FOREIGN KEY ("SALA_ID")
	  REFERENCES "CMX_SALA" ("SALA_ID") ENABLE;