
  CREATE TABLE "CMX_TEACHER" 
   (	"TEACHER_ID" NUMBER, 
	"NAME" VARCHAR2(100), 
	"PHONE" VARCHAR2(100), 
	"CEP" VARCHAR2(100), 
	"LOGRADOURO" VARCHAR2(100), 
	"UF" VARCHAR2(3), 
	 CONSTRAINT "CMX_TEACHER_PK" PRIMARY KEY ("TEACHER_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CMX_TEACHER_UK" UNIQUE ("NAME")
  USING INDEX  ENABLE
   ) ;